global:
  scrape_interval: 2s
  evaluation_interval: 2s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "app"
    static_configs:
      - targets: [ "172.17.0.1:2112" ]