run:
  timeout: 5m
  build-tags: ""
  skip-dirs-use-default: false
  skip-files:
    - '.*_test.go'

build:
  no-vcs: true

output:
  format: colored-line-number
  print-issued-lines: true

linters:
  enable:
    - revive
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - staticcheck
    - funlen
    - unparam
    - dupl
    - ineffassign
    - prealloc
    - bodyclose
    - gocritic

issues:
  exclude:
    - "error return value not checked.*(Close|Log|Exit)"
    - "should have 2 args, not 3"
  exclude-dirs:
    - vendor.protogen
    - pkg
    - bin

max-line-length: 120

gofmt:
  simplify: true

misspell:
  locale: en_US

funlen:
  lines: 500
  statements: 60
  comments: 5
  ignore_tests: true

revive:
  confidence: 0.8
  severity: warning
  rules:
    - name: indent-error-flow
    - name: var-naming
    - name: blank-imports
    - name: import-shadowing
    - name: time-naming
    - name: dot-imports
    - name: error-return
    - name: range-val-in-closure

gocritic:
  enabled-checks:
    - commentFormatting
    - ifElseChain
    - sloppyLen
    - dupImport
    - hugeParam
    - captLocal
    - typeSwitchVar
    - whyNoLint